// src/components/FinancialCard.tsx
import React from 'react';
import svgPaths from "../imports/svg-h9t05zbsew";

interface FinancialData {
  dates: string[];
  values: number[];
  result: number;
}

interface FinancialCardProps {
  title: string;
  data: FinancialData;
  globalSelectedYears: string[];
}

export const FinancialCard: React.FC<FinancialCardProps> = ({ 
  title, 
  data, 
  globalSelectedYears 
}) => {
  // Filter data based on selected years
  const filteredData = data.dates
    .map((date, index) => ({
      date,
      value: data.values[index],
      index
    }))
    .filter(item => globalSelectedYears.includes(item.date))
    .sort((a, b) => parseInt(a.date) - parseInt(b.date));

  const formatNumber = (num: number): string => {
    return new Intl.NumberFormat('es-ES').format(num);
  };

  // Generar datos para las filas adicionales manteniendo la estructura del CajaFinal
  const generateRowData = (baseValues: number[], multiplier: number = 1) => {
    return baseValues.map(value => Math.round(value * multiplier));
  };

  // Function to format the year display in the selector
  const formatYearDisplay = (years: string[]): string => {
    if (years.length === 0) return '2022-2027';
    if (years.length === 1) return years[0];
    return `${years[0]}-${years[years.length - 1]}`;
  };

  return (
    <div 
      className="financial-card relative rounded-[18.9259px]"
      style={{ minWidth: '370px', width: '370px' }}
    >
      <div className="min-w-inherit relative size-full">
        <div className="box-border content-stretch flex flex-col gap-[9px] items-start justify-start min-w-inherit overflow-clip p-[12px] relative size-full">
          
          {/* Header Frame - EXACTO DEL CAJA FINAL */}
          <div className="min-w-[370px] relative shrink-0 w-full">
            <div className="flex flex-row items-center justify-center min-w-inherit overflow-clip relative size-full">
              <div className="box-border content-stretch flex flex-row gap-3 items-center justify-center min-w-inherit p-[6px] relative w-full">
                
                {/* Título */}
                <div className="basis-0 grow min-h-px min-w-px relative shrink-0">
                  <div className="box-border content-stretch flex flex-row gap-3 items-center justify-start p-0 relative w-full">
                    <div className="font-['Inter:Regular',_sans-serif] font-normal leading-[0] not-italic relative shrink-0 text-[#9d9292] text-[16px] text-left text-nowrap dark:text-[#adadad]">
                      <p className="block leading-[normal] whitespace-pre">{title}</p>
                    </div>
                  </div>
                </div>
                
                {/* Selector de años - ADAPTABLE */}
                <div className="financial-card-select h-10 min-w-[100px] relative rounded-lg shrink-0">
                  <div className="absolute financial-card-select-border border border-solid inset-[-0.5px] pointer-events-none rounded-[8.5px]" />
                  <div className="flex flex-row items-center min-w-inherit relative size-full">
                    <div className="[flex-flow:wrap] box-border content-center flex gap-2 h-10 items-center justify-start min-w-inherit pl-4 pr-3 py-3 relative">
                      <div className="font-['Inter:Medium',_sans-serif] font-medium leading-[0] not-italic relative shrink-0 text-[14px] text-left financial-card-select-text text-nowrap">
                        <p className="block leading-[normal] whitespace-pre">
                          {formatYearDisplay(globalSelectedYears)}
                        </p>
                      </div>
                      
                      {/* Chevron Down */}
                      <div className="relative shrink-0 size-4">
                        <svg className="block size-full" fill="none" preserveAspectRatio="none" viewBox="0 0 16 16">
                          <g>
                            <path
                              d="M4 6L8 10L12 6"
                              className="financial-card-chevron"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeWidth="1.6"
                            />
                          </g>
                        </svg>
                      </div>
                    </div>
                  </div>
                </div>
                
                {/* Drag Gripper - ADAPTABLE CON TOOLTIP */}
                <div 
                  className="relative shrink-0 size-6 drag-handle group cursor-move"
                  title="Arrastra para reordenar"
                  aria-label="Mover tarjeta"
                >
                  <svg className="block size-full transition-all duration-200 group-hover:scale-110" fill="none" preserveAspectRatio="none" viewBox="0 0 24 24">
                    <g>
                      <path
                        clipRule="evenodd"
                        d={svgPaths.p1e1c14f0}
                        className="financial-card-gripper"
                        fillRule="evenodd"
                      />
                    </g>
                  </svg>
                  
                  {/* Tooltip para mostrar funcionalidad */}
                  <div className="absolute -top-8 -left-12 px-2 py-1 bg-black text-white text-xs rounded opacity-0 group-hover:opacity-100 transition-opacity duration-200 pointer-events-none whitespace-nowrap z-50">
                    Arrastra aquí
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Fechas Header - ADAPTABLE */}
          <div className="h-[34.111px] relative shrink-0 w-full">
            <div className="absolute border-[0px_0px_0.8px] border-dashed financial-card-border-dashed inset-0 pointer-events-none" />
            <div className="flex flex-row items-center relative size-full">
              <div className="box-border content-stretch flex flex-row h-[34.111px] items-center justify-start pb-2 pt-0 px-0 relative w-full">
                {filteredData.map((item) => (
                  <div key={item.date} className="basis-0 grow min-h-px min-w-px relative shrink-0">
                    <div className="flex flex-row items-center justify-center relative size-full">
                      <div className="box-border content-stretch flex flex-row gap-2.5 items-center justify-center p-[4px] relative w-full">
                        <div className="font-['Inter:Medium',_sans-serif] font-medium leading-[0] not-italic relative shrink-0 text-[14px] text-left financial-card-date-text text-nowrap">
                          <p className="block leading-[normal] whitespace-pre">{item.date}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Resultado Principal - ADAPTABLE */}
          <div className="h-[34.111px] relative shrink-0 w-full">
            <div className="absolute border-[0px_0px_0.8px] border-dashed financial-card-border-dashed inset-0 pointer-events-none" />
            <div className="flex flex-row items-center justify-center relative size-full">
              <div className="box-border content-stretch flex flex-row gap-2.5 h-[34.111px] items-center justify-center pb-2 pt-1 px-1 relative w-full">
                <div className="font-['Inter:Medium',_sans-serif] font-medium leading-[0] not-italic relative shrink-0 text-[#b00020] dark:text-[#ff2e2e] text-[28px] text-left text-nowrap">
                  <p className="block leading-[normal] whitespace-pre">{formatNumber(data.result)}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Primera Fila de Cantidades - ADAPTABLE */}
          <div className="h-[34.111px] relative shrink-0 w-full">
            <div className="absolute border-[0px_0px_0.8px] border-dashed financial-card-border-dashed inset-0 pointer-events-none" />
            <div className="flex flex-row items-center relative size-full">
              <div className="box-border content-stretch flex flex-row h-[34.111px] items-center justify-start pb-2 pt-0 px-0 relative w-full">
                
                {/* Primera cantidad */}
                <div className="basis-0 grow h-full min-h-px min-w-px relative shrink-0">
                  <div className="flex flex-row items-center justify-center relative size-full">
                    <div className="box-border content-stretch flex flex-row gap-2.5 items-center justify-center px-0 py-1 relative size-full">
                      <div className="font-['Inter:Regular',_sans-serif] font-normal leading-[0] not-italic relative shrink-0 text-[#2e649d] dark:text-[#3acfff] text-[12px] text-left text-nowrap">
                        <p className="block leading-[normal] whitespace-pre">
                          {filteredData.length > 0 ? formatNumber(filteredData[0].value) : '147.950'}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Cantidades del medio (repetir el patrón del diseño) */}
                {filteredData.slice(1, -1).map((item, index) => (
                  <div key={`cantidad-${index}`} className="basis-0 financial-card-transparent-bg grow h-full min-h-px min-w-px relative shrink-0">
                    <div className="flex flex-row items-center justify-center relative size-full">
                      <div className="box-border content-stretch flex flex-row gap-2.5 items-center justify-center px-0 py-1 relative size-full">
                        <div className="font-['Inter:Regular',_sans-serif] font-normal leading-[0] not-italic relative shrink-0 text-[#2e649d] dark:text-[#3acfff] text-[12px] text-left text-nowrap">
                          <p className="block leading-[normal] whitespace-pre">{formatNumber(item.value)}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}

                {/* Última cantidad */}
                {filteredData.length > 1 && (
                  <div className="basis-0 financial-card-transparent-bg grow h-full min-h-px min-w-px relative shrink-0">
                    <div className="flex flex-row items-center justify-center relative size-full">
                      <div className="box-border content-stretch flex flex-row gap-2.5 items-center justify-center p-[4px] relative size-full">
                        <div className="font-['Inter:Regular',_sans-serif] font-normal leading-[0] not-italic relative shrink-0 text-[#2e649d] dark:text-[#3acfff] text-[12px] text-left text-nowrap">
                          <p className="block leading-[normal] whitespace-pre">
                            {formatNumber(filteredData[filteredData.length - 1].value)}
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Segunda Fila de Cantidades - REPITIENDO EL PATRÓN */}
          <div className="h-[34.111px] relative shrink-0 w-full">
            <div className="absolute border-[0px_0px_0.8px] border-dashed financial-card-border-dashed inset-0 pointer-events-none" />
            <div className="flex flex-row items-center relative size-full">
              <div className="box-border content-stretch flex flex-row h-[34.111px] items-center justify-start pb-2 pt-0 px-0 relative w-full">
                
                {generateRowData(filteredData.map(item => item.value), 1.1).map((value, index) => (
                  <div key={`row2-${index}`} className={`basis-0 ${index === 0 ? '' : 'financial-card-transparent-bg'} grow h-full min-h-px min-w-px relative shrink-0`}>
                    <div className="flex flex-row items-center justify-center relative size-full">
                      <div className={`box-border content-stretch flex flex-row gap-2.5 items-center justify-center ${index < 2 ? 'px-0 py-1' : 'p-[4px]'} relative size-full`}>
                        <div className="font-['Inter:Regular',_sans-serif] font-normal leading-[0] not-italic relative shrink-0 text-[#2e649d] dark:text-[#3acfff] text-[12px] text-left text-nowrap">
                          <p className="block leading-[normal] whitespace-pre">{formatNumber(value)}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
      
      {/* Border y shadow ADAPTATIVOS */}
      <div className="absolute financial-card-outer-border border border-solid inset-0 pointer-events-none rounded-[18.9259px] financial-card-shadow" />
    </div>
  );
};

// src/components/financial-card/financial-card.component.ts
import { Component, Input, OnInit, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FinancialData } from '../../interfaces/financial.interfaces';

@Component({
  selector: 'app-financial-card',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="bg-[#ffffff] relative rounded-[20px] financial-card draggable"
         style="min-width: 390px; max-width: 390px; width: 390px; height: 245px;">
      
      <!-- Border and shadow effects -->
      <div class="absolute border border-[#e0e0e0] border-solid inset-0 pointer-events-none rounded-[20px] shadow-[0px_4px_4px_0px_rgba(0,0,0,0.04)]"></div>
      
      <div class="relative size-full">
        <div class="box-border content-stretch flex flex-col gap-4 items-start justify-start p-6 relative size-full">
          
          <!-- Header with drag handle and title -->
          <div class="relative shrink-0 w-full">
            <div class="box-border content-stretch flex flex-row gap-2.5 items-start justify-between p-0 relative w-full">
              
              <!-- Drag handle -->
              <div class="drag-handle cursor-move relative shrink-0 size-6" 
                   title="Arrastrar para reordenar">
                <svg class="block size-full" fill="none" preserveAspectRatio="none" viewBox="0 0 24 24">
                  <g>
                    <circle cx="7" cy="7" r="1" fill="#9e9e9e"/>
                    <circle cx="7" cy="12" r="1" fill="#9e9e9e"/>
                    <circle cx="7" cy="17" r="1" fill="#9e9e9e"/>
                    <circle cx="12" cy="7" r="1" fill="#9e9e9e"/>
                    <circle cx="12" cy="12" r="1" fill="#9e9e9e"/>
                    <circle cx="12" cy="17" r="1" fill="#9e9e9e"/>
                    <circle cx="17" cy="7" r="1" fill="#9e9e9e"/>
                    <circle cx="17" cy="12" r="1" fill="#9e9e9e"/>
                    <circle cx="17" cy="17" r="1" fill="#9e9e9e"/>
                  </g>
                </svg>
              </div>
              
              <!-- Card title -->
              <div class="basis-0 grow min-h-px min-w-px relative shrink-0">
                <div class="font-['Inter:Regular',_sans-serif] font-normal leading-[0] not-italic relative shrink-0 text-[#9d9292] text-[16px] text-left w-full">
                  <p class="block leading-[normal] card-title">{{ title }}</p>
                </div>
              </div>
            </div>
          </div>

          <!-- Values display -->
          <div class="relative shrink-0 w-full">
            <div class="box-border content-stretch flex flex-row gap-4 items-start justify-start p-0 relative w-full">
              
              <!-- Years column -->
              <div class="basis-0 grow min-h-px min-w-px relative shrink-0">
                <div class="box-border content-stretch flex flex-col gap-2 items-start justify-start p-0 relative w-full">
                  <div *ngFor="let year of filteredYears(); let i = index" class="relative shrink-0 w-full">
                    <div class="font-['Inter:Medium',_sans-serif] font-medium leading-[0] not-italic relative shrink-0 text-[#374151] text-[14px] text-left w-full">
                      <p class="block leading-[normal] year-label">{{ year }}</p>
                    </div>
                  </div>
                </div>
              </div>

              <!-- Values column -->
              <div class="basis-0 grow min-h-px min-w-px relative shrink-0">
                <div class="box-border content-stretch flex flex-col gap-2 items-end justify-start p-0 relative w-full">
                  <div *ngFor="let value of filteredValues(); let i = index" class="relative shrink-0 w-full">
                    <div class="font-['Inter:Regular',_sans-serif] font-normal leading-[0] not-italic relative shrink-0 text-[#2e649d] text-[12px] text-right w-full">
                      <p class="block leading-[normal] value-text">{{ formatNumber(value) }}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Result section -->
          <div class="relative shrink-0 w-full">
            <div class="box-border content-stretch flex flex-col gap-1 items-start justify-start p-0 relative w-full">
              <div class="font-['Inter:Regular',_sans-serif] font-normal leading-[0] not-italic relative shrink-0 text-[#9d9292] text-[14px] text-left w-full">
                <p class="block leading-[normal]">Resultado 2024</p>
              </div>
              <div class="font-['Inter:Medium',_sans-serif] font-medium leading-[0] not-italic relative shrink-0 text-[#b00020] text-[28px] text-left w-full">
                <p class="block leading-[normal] result-number">{{ formatNumber(data.result) }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./financial-card.component.css']
})
export class FinancialCardComponent implements OnInit {
  @Input() title: string = '';
  @Input() data!: FinancialData;
  @Input() globalSelectedYears: string[] = [];

  // Computed properties for filtered data
  filteredYears = computed(() => {
    if (this.globalSelectedYears.length === 0) {
      return this.data.dates;
    }
    return this.data.dates.filter(date => this.globalSelectedYears.includes(date));
  });

  filteredValues = computed(() => {
    if (this.globalSelectedYears.length === 0) {
      return this.data.values;
    }
    const filteredIndices = this.data.dates
      .map((date, index) => this.globalSelectedYears.includes(date) ? index : -1)
      .filter(index => index !== -1);
    return filteredIndices.map(index => this.data.values[index]);
  });

  ngOnInit(): void {
    if (!this.data) {
      console.error('FinancialCard: data input is required');
    }
  }

  formatNumber(value: number): string {
    if (value >= 1000000) {
      return (value / 1000000).toFixed(1) + 'M';
    } else if (value >= 1000) {
      return (value / 1000).toFixed(1) + 'K';
    }
    return value.toLocaleString();
  }
}
